'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IPaymentService")>  _
    Public Interface IPaymentService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/GetData", ReplyAction:="http://tempuri.org/IPaymentService/GetDataResponse")>  _
        Function GetData(ByVal value As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/GetData", ReplyAction:="http://tempuri.org/IPaymentService/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrievePaymentDetail", ReplyAction:="http://tempuri.org/IPaymentService/RetrievePaymentDetailResponse")>  _
        Function RetrievePaymentDetail(ByVal paymentDetail As System.IO.Stream) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrievePaymentDetail", ReplyAction:="http://tempuri.org/IPaymentService/RetrievePaymentDetailResponse")>  _
        Function RetrievePaymentDetailAsync(ByVal paymentDetail As System.IO.Stream) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrievePaymentPageInfo", ReplyAction:="http://tempuri.org/IPaymentService/RetrievePaymentPageInfoResponse")>  _
        Function RetrievePaymentPageInfo(ByVal userID As Integer, ByVal bookID As String, ByVal quantity As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrievePaymentPageInfo", ReplyAction:="http://tempuri.org/IPaymentService/RetrievePaymentPageInfoResponse")>  _
        Function RetrievePaymentPageInfoAsync(ByVal userID As Integer, ByVal bookID As String, ByVal quantity As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrievePaymentPageInfoEmail", ReplyAction:="http://tempuri.org/IPaymentService/RetrievePaymentPageInfoEmailResponse")>  _
        Function RetrievePaymentPageInfoEmail(ByVal userID As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrievePaymentPageInfoEmail", ReplyAction:="http://tempuri.org/IPaymentService/RetrievePaymentPageInfoEmailResponse")>  _
        Function RetrievePaymentPageInfoEmailAsync(ByVal userID As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrieveCartPageInfo", ReplyAction:="http://tempuri.org/IPaymentService/RetrieveCartPageInfoResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Byte())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ModelLibrary.BookCartCombined())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ModelLibrary.BookCartCombined)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ModelLibrary.BookWishlistCombined())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ModelLibrary.BookWishlistCombined))>  _
        Function RetrieveCartPageInfo(ByVal userID As Object) As ModelLibrary.BookCartCombined()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrieveCartPageInfo", ReplyAction:="http://tempuri.org/IPaymentService/RetrieveCartPageInfoResponse")>  _
        Function RetrieveCartPageInfoAsync(ByVal userID As Object) As System.Threading.Tasks.Task(Of ModelLibrary.BookCartCombined())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/CalculateTotalPrice", ReplyAction:="http://tempuri.org/IPaymentService/CalculateTotalPriceResponse")>  _
        Function CalculateTotalPrice(ByVal items() As ModelLibrary.BookCartCombined) As Decimal
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/CalculateTotalPrice", ReplyAction:="http://tempuri.org/IPaymentService/CalculateTotalPriceResponse")>  _
        Function CalculateTotalPriceAsync(ByVal items() As ModelLibrary.BookCartCombined) As System.Threading.Tasks.Task(Of Decimal)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/DeleteZeroCartItem", ReplyAction:="http://tempuri.org/IPaymentService/DeleteZeroCartItemResponse")>  _
        Function DeleteZeroCartItem(ByVal userID As Integer, ByVal bookID As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/DeleteZeroCartItem", ReplyAction:="http://tempuri.org/IPaymentService/DeleteZeroCartItemResponse")>  _
        Function DeleteZeroCartItemAsync(ByVal userID As Integer, ByVal bookID As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/SaveCartChangesToDB", ReplyAction:="http://tempuri.org/IPaymentService/SaveCartChangesToDBResponse")>  _
        Function SaveCartChangesToDB(ByVal userID As Integer, ByVal quantity As Integer, ByVal bookID As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/SaveCartChangesToDB", ReplyAction:="http://tempuri.org/IPaymentService/SaveCartChangesToDBResponse")>  _
        Function SaveCartChangesToDBAsync(ByVal userID As Integer, ByVal quantity As Integer, ByVal bookID As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/CheckBookQuantity", ReplyAction:="http://tempuri.org/IPaymentService/CheckBookQuantityResponse")>  _
        Function CheckBookQuantity(ByVal bookID As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/CheckBookQuantity", ReplyAction:="http://tempuri.org/IPaymentService/CheckBookQuantityResponse")>  _
        Function CheckBookQuantityAsync(ByVal bookID As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrieveWishlistPageInfo", ReplyAction:="http://tempuri.org/IPaymentService/RetrieveWishlistPageInfoResponse")>  _
        Function RetrieveWishlistPageInfo(ByVal userID As Integer) As ModelLibrary.BookWishlistCombined()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RetrieveWishlistPageInfo", ReplyAction:="http://tempuri.org/IPaymentService/RetrieveWishlistPageInfoResponse")>  _
        Function RetrieveWishlistPageInfoAsync(ByVal userID As Integer) As System.Threading.Tasks.Task(Of ModelLibrary.BookWishlistCombined())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RemoveFromWishlist", ReplyAction:="http://tempuri.org/IPaymentService/RemoveFromWishlistResponse")>  _
        Function RemoveFromWishlist(ByVal userID As Integer, ByVal bookID As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaymentService/RemoveFromWishlist", ReplyAction:="http://tempuri.org/IPaymentService/RemoveFromWishlistResponse")>  _
        Function RemoveFromWishlistAsync(ByVal userID As Integer, ByVal bookID As Integer) As System.Threading.Tasks.Task(Of Integer)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPaymentServiceChannel
        Inherits ServiceReference1.IPaymentService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PaymentServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IPaymentService)
        Implements ServiceReference1.IPaymentService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As String) As String Implements ServiceReference1.IPaymentService.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As String) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IPaymentService.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function RetrievePaymentDetail(ByVal paymentDetail As System.IO.Stream) As Boolean Implements ServiceReference1.IPaymentService.RetrievePaymentDetail
            Return MyBase.Channel.RetrievePaymentDetail(paymentDetail)
        End Function
        
        Public Function RetrievePaymentDetailAsync(ByVal paymentDetail As System.IO.Stream) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.IPaymentService.RetrievePaymentDetailAsync
            Return MyBase.Channel.RetrievePaymentDetailAsync(paymentDetail)
        End Function
        
        Public Function RetrievePaymentPageInfo(ByVal userID As Integer, ByVal bookID As String, ByVal quantity As Integer) As String Implements ServiceReference1.IPaymentService.RetrievePaymentPageInfo
            Return MyBase.Channel.RetrievePaymentPageInfo(userID, bookID, quantity)
        End Function
        
        Public Function RetrievePaymentPageInfoAsync(ByVal userID As Integer, ByVal bookID As String, ByVal quantity As Integer) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IPaymentService.RetrievePaymentPageInfoAsync
            Return MyBase.Channel.RetrievePaymentPageInfoAsync(userID, bookID, quantity)
        End Function
        
        Public Function RetrievePaymentPageInfoEmail(ByVal userID As Integer) As String Implements ServiceReference1.IPaymentService.RetrievePaymentPageInfoEmail
            Return MyBase.Channel.RetrievePaymentPageInfoEmail(userID)
        End Function
        
        Public Function RetrievePaymentPageInfoEmailAsync(ByVal userID As Integer) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IPaymentService.RetrievePaymentPageInfoEmailAsync
            Return MyBase.Channel.RetrievePaymentPageInfoEmailAsync(userID)
        End Function
        
        Public Function RetrieveCartPageInfo(ByVal userID As Object) As ModelLibrary.BookCartCombined() Implements ServiceReference1.IPaymentService.RetrieveCartPageInfo
            Return MyBase.Channel.RetrieveCartPageInfo(userID)
        End Function
        
        Public Function RetrieveCartPageInfoAsync(ByVal userID As Object) As System.Threading.Tasks.Task(Of ModelLibrary.BookCartCombined()) Implements ServiceReference1.IPaymentService.RetrieveCartPageInfoAsync
            Return MyBase.Channel.RetrieveCartPageInfoAsync(userID)
        End Function
        
        Public Function CalculateTotalPrice(ByVal items() As ModelLibrary.BookCartCombined) As Decimal Implements ServiceReference1.IPaymentService.CalculateTotalPrice
            Return MyBase.Channel.CalculateTotalPrice(items)
        End Function
        
        Public Function CalculateTotalPriceAsync(ByVal items() As ModelLibrary.BookCartCombined) As System.Threading.Tasks.Task(Of Decimal) Implements ServiceReference1.IPaymentService.CalculateTotalPriceAsync
            Return MyBase.Channel.CalculateTotalPriceAsync(items)
        End Function
        
        Public Function DeleteZeroCartItem(ByVal userID As Integer, ByVal bookID As Integer) As Boolean Implements ServiceReference1.IPaymentService.DeleteZeroCartItem
            Return MyBase.Channel.DeleteZeroCartItem(userID, bookID)
        End Function
        
        Public Function DeleteZeroCartItemAsync(ByVal userID As Integer, ByVal bookID As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.IPaymentService.DeleteZeroCartItemAsync
            Return MyBase.Channel.DeleteZeroCartItemAsync(userID, bookID)
        End Function
        
        Public Function SaveCartChangesToDB(ByVal userID As Integer, ByVal quantity As Integer, ByVal bookID As Integer) As Boolean Implements ServiceReference1.IPaymentService.SaveCartChangesToDB
            Return MyBase.Channel.SaveCartChangesToDB(userID, quantity, bookID)
        End Function
        
        Public Function SaveCartChangesToDBAsync(ByVal userID As Integer, ByVal quantity As Integer, ByVal bookID As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference1.IPaymentService.SaveCartChangesToDBAsync
            Return MyBase.Channel.SaveCartChangesToDBAsync(userID, quantity, bookID)
        End Function
        
        Public Function CheckBookQuantity(ByVal bookID As Integer) As Integer Implements ServiceReference1.IPaymentService.CheckBookQuantity
            Return MyBase.Channel.CheckBookQuantity(bookID)
        End Function
        
        Public Function CheckBookQuantityAsync(ByVal bookID As Integer) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReference1.IPaymentService.CheckBookQuantityAsync
            Return MyBase.Channel.CheckBookQuantityAsync(bookID)
        End Function
        
        Public Function RetrieveWishlistPageInfo(ByVal userID As Integer) As ModelLibrary.BookWishlistCombined() Implements ServiceReference1.IPaymentService.RetrieveWishlistPageInfo
            Return MyBase.Channel.RetrieveWishlistPageInfo(userID)
        End Function
        
        Public Function RetrieveWishlistPageInfoAsync(ByVal userID As Integer) As System.Threading.Tasks.Task(Of ModelLibrary.BookWishlistCombined()) Implements ServiceReference1.IPaymentService.RetrieveWishlistPageInfoAsync
            Return MyBase.Channel.RetrieveWishlistPageInfoAsync(userID)
        End Function
        
        Public Function RemoveFromWishlist(ByVal userID As Integer, ByVal bookID As Integer) As Integer Implements ServiceReference1.IPaymentService.RemoveFromWishlist
            Return MyBase.Channel.RemoveFromWishlist(userID, bookID)
        End Function
        
        Public Function RemoveFromWishlistAsync(ByVal userID As Integer, ByVal bookID As Integer) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReference1.IPaymentService.RemoveFromWishlistAsync
            Return MyBase.Channel.RemoveFromWishlistAsync(userID, bookID)
        End Function
    End Class
End Namespace
